name: 'Sakura vpn checkin bot'

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  sakuraCheckin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools requests beautifulsoup4
      - name: 'sakura checkin'
        env: 
          SAKURA_USER: ${{ secrets.SAKURA_USER }}
          SAKURA_PASSWD: ${{ secrets.SAKURA_PASSWD }}
        run: python sakura-vpn/checkin.py

